module.exports = Object.freeze({
  TYPE_DIRECT: "DIRECT",
  TYPE_GROUP: "GROUP",
  ROLE_ADMIN: "ADMIN",
  ROLE_MEMBER: "MEMBER",
  STATUS_ACTIVE: 1,
  STATUS_INACTIVE: 0,
  MIN_GROUP_MEMBERS: 3,
  MAX_GROUP_MEMBERS: 1024,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 50,
  ERRORS: {
    INVALID_PARTICIPANT: "INVALID_PARTICIPANT",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    INVALID_CURSOR: "INVALID_CURSOR",
    GROUP_NOT_FOUND: "GROUP_NOT_FOUND",
    GROUP_ADMIN_REQUIRED: "GROUP_ADMIN_REQUIRED",
    GROUP_MEMBER_NOT_FOUND: "GROUP_MEMBER_NOT_FOUND"
  }
});
