module.exports = Object.freeze({
  TYPE_DIRECT: "DIRECT",
  STATUS_ACTIVE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 50,
  ERRORS: {
    INVALID_PARTICIPANT: "INVALID_PARTICIPANT",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    INVALID_CURSOR: "INVALID_CURSOR"
  }
});
