module.exports = Object.freeze({
  MESSAGE_TYPE_TEXT: "TEXT",
  ENCRYPTION_VERSION_SIGNAL_V1: "SIGNAL_V1",
  CIPHERTEXT_TYPES: Object.freeze(["PREKEY", "SIGNAL"]),
  MAX_ENVELOPES: 50,
  MAX_CIPHERTEXT_BYTES: 256 * 1024,
  DEFAULT_SYNC_LIMIT: 50,
  MAX_SYNC_LIMIT: 100,
  DEFAULT_HISTORY_LIMIT: 30,
  MAX_HISTORY_LIMIT: 100
});
