module.exports = Object.freeze({
  CONVERSATION_NOT_FOUND: "CONVERSATION_NOT_FOUND",
  NOT_CONVERSATION_MEMBER: "NOT_CONVERSATION_MEMBER",
  INVALID_RECIPIENT: "INVALID_RECIPIENT",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  DEVICE_REVOKED: "DEVICE_REVOKED",
  PREKEY_BUNDLE_NOT_FOUND: "PREKEY_BUNDLE_NOT_FOUND",
  INVALID_MESSAGE: "INVALID_MESSAGE",
  MESSAGE_TOO_LARGE: "MESSAGE_TOO_LARGE",
  MESSAGE_NOT_FOUND: "MESSAGE_NOT_FOUND",
  DUPLICATE_MESSAGE: "DUPLICATE_MESSAGE",
  UNAUTHORIZED_MESSAGE_ACCESS: "UNAUTHORIZED_MESSAGE_ACCESS"
});
