module.exports = Object.freeze({
  ACTIVATION_TTL_MINUTES: 30,
  ACTIVATION_CODE_TTL_HOURS: 24,
  ACCESS_TOKEN_TTL: "15m",
  REFRESH_TOKEN_TTL_DAYS: 30,
  ACTIVATION_RATE_LIMIT: 5,
  ACTIVATION_RATE_WINDOW_SECONDS: 15 * 60,
  MAX_ONE_TIME_PREKEYS: 100,
  PREKEY_LOW_THRESHOLD: 20
});
