module.exports = Object.freeze({
  DEVICE_REVOKED: "device:revoked",
  USER_ONLINE: "USER_ONLINE",
  USER_OFFLINE: "USER_OFFLINE",
  PRESENCE_UPDATE: "PRESENCE_UPDATE",
  PRESENCE_SUBSCRIBE: "PRESENCE_SUBSCRIBE",
  PRESENCE_UNSUBSCRIBE: "PRESENCE_UNSUBSCRIBE",
  PRESENCE_ERROR: "PRESENCE_ERROR",
  MESSAGE_SEND: "MESSAGE_SEND",
  MESSAGE_NEW: "MESSAGE_NEW",
  MESSAGE_DELIVERED: "MESSAGE_DELIVERED",
  MESSAGE_READ: "MESSAGE_READ",
  CONVERSATION_DELETED: "CONVERSATION_DELETED",
  TYPING_START: "TYPING_START",
  TYPING_STOP: "TYPING_STOP",
  TYPING_UPDATE: "TYPING_UPDATE",
  SESSION_REVOKED: "SESSION_REVOKED"
});
